package org.open.corejava.projecteuler;

/**
 * @author Mahadev Mane
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

public class ProjectEulerP2S1 {
    private static final int LIMIT = 4000000;

    public static void main(String[] args) {
        int nt = 2, t1 = 1, t2 = 2;
        int sum = 0;

        while (nt <= LIMIT) {
            nt = t1 + t2;

            if (nt % 2 == 0) {
                sum += nt;
            }

            t1 = t2;
            t2 = nt;
        }

        System.out.println(sum);
    }
}